-------------------------------------------------------------------------------
-- Dice Master (C) 2023 <The League of Lordaeron> - Moon Guard
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
-- Combat data imported from Azure-Peak.
-- This file intentionally ports only the base data layer:
--   * characteristics
--   * portable combat intent definitions
--   * weapon intent archetypes
-- Source repository: C:\Axis\Azure-Peak
-------------------------------------------------------------------------------

local Me = DiceMaster4

if not Me then
	return
end

local CombatData = Me.CombatData or {}
Me.CombatData = CombatData

CombatData.SchemaVersion = 1
CombatData.Source = {
	name = "Azure-Peak",
	path = "C:\\Axis\\Azure-Peak",
	scope = "Base combat vocabulary only",
	importedOn = "2026-03-09",
}

local function DeepCopy(value)
	if type(value) ~= "table" then
		return value
	end

	local copy = {}

	for key, nestedValue in pairs(value) do
		copy[key] = DeepCopy(nestedValue)
	end

	return copy
end

local INTENT_DEFAULTS = {
	name = "intent",
	description = "",
	group = "generic",
	iconState = "instrike",
	attackVerbs = { "hits", "strikes" },
	animation = "strike",
	damageClass = "blunt",
	damageType = "blunt",
	accuracyModifier = 0,
	canParry = true,
	canDodge = true,
	chargeTime = 0,
	chargeDrain = 0,
	releaseDrain = 1,
	missCost = 1,
	clickCooldown = nil,
	sourceClickCooldown = "CLICK_CD_MELEE",
	recovery = 0,
	swingDelay = 0,
	damageFactor = 1,
	penetrationFactor = 0,
	integrityDamageFactor = 1,
	minDamage = 0,
	maxDamage = 200,
	reach = 1,
	allowOffhand = true,
	peelDivisor = 0,
	isRanged = false,
	isGuard = false,
	isUnarmed = false,
	suppressesAutoAim = false,
	baseAimTime = nil,
	sourcePath = "",
	notes = nil,
}

local function DefineIntent(intentId, definition)
	local intent = DeepCopy(INTENT_DEFAULTS)

	for key, value in pairs(definition) do
		intent[key] = DeepCopy(value)
	end

	if definition.clickCooldown ~= nil and definition.sourceClickCooldown == nil then
		intent.sourceClickCooldown = nil
	end

	intent.id = intentId

	return intent
end

-------------------------------------------------------------------------------
-- Characteristics.
-- Azure-Peak uses a seven-stat backbone with a 10-point baseline and a
-- clamped 1-20 live range.
-------------------------------------------------------------------------------

CombatData.StatOrder = {
	"strength",
	"perception",
	"intelligence",
	"constitution",
	"willpower",
	"speed",
	"fortune",
}

CombatData.Stats = {
	strength = {
		id = "strength",
		label = "Strength",
		shortLabel = "STR",
		defaultValue = 10,
		minValue = 1,
		maxValue = 20,
		sourceDefine = "STAT_STRENGTH",
		sourceVar = "STASTR",
		description = "Raw power, force delivery, and physical leverage.",
	},
	perception = {
		id = "perception",
		label = "Perception",
		shortLabel = "PER",
		defaultValue = 10,
		minValue = 1,
		maxValue = 20,
		sourceDefine = "STAT_PERCEPTION",
		sourceVar = "STAPER",
		description = "Awareness, aim quality, and battlefield reading.",
	},
	intelligence = {
		id = "intelligence",
		label = "Intelligence",
		shortLabel = "INT",
		defaultValue = 10,
		minValue = 1,
		maxValue = 20,
		sourceDefine = "STAT_INTELLIGENCE",
		sourceVar = "STAINT",
		description = "Planning, technical control, and learning depth.",
	},
	constitution = {
		id = "constitution",
		label = "Constitution",
		shortLabel = "CON",
		defaultValue = 10,
		minValue = 1,
		maxValue = 20,
		sourceDefine = "STAT_CONSTITUTION",
		sourceVar = "STACON",
		description = "Durability, stamina reserve, and bodily resilience.",
	},
	willpower = {
		id = "willpower",
		label = "Willpower",
		shortLabel = "WIL",
		defaultValue = 10,
		minValue = 1,
		maxValue = 20,
		sourceDefine = "STAT_WILLPOWER",
		sourceVar = "STAWIL",
		description = "Pain tolerance, focus, and mental endurance.",
	},
	speed = {
		id = "speed",
		label = "Speed",
		shortLabel = "SPD",
		defaultValue = 10,
		minValue = 1,
		maxValue = 20,
		sourceDefine = "STAT_SPEED",
		sourceVar = "STASPD",
		description = "Tempo, movement sharpness, and reaction pace.",
	},
	fortune = {
		id = "fortune",
		label = "Fortune",
		shortLabel = "FRT",
		defaultValue = 10,
		minValue = 1,
		maxValue = 20,
		sourceDefine = "STAT_FORTUNE",
		sourceVar = "STALUC",
		description = "Luck-adjacent edge, fate bias, and favorable breaks.",
	},
}

-------------------------------------------------------------------------------
-- Intent schema.
-- This is a normalized, data-only view of the Azure-Peak intent datums.
-------------------------------------------------------------------------------

CombatData.IntentSchema = {
	id = "Stable DiceMaster identifier for the intent.",
	group = "High-level family such as sword, dagger, unarmed, or crossbow.",
	name = "Display name of the intent.",
	description = "Optional text carried over when the source intent defined one.",
	iconState = "Source icon_state token for the intent button.",
	attackVerbs = "List of combat log verbs associated with the action.",
	animation = "Named swing style used by the source combat animation.",
	damageClass = "Normalized blade or impact class.",
	damageType = "Portable damage pressure type: blunt, slash, or stab.",
	accuracyModifier = "Additive accuracy modifier from the source datum.",
	canParry = "Whether the source intent can be parried against.",
	canDodge = "Whether the source intent can be dodged against.",
	chargeTime = "Base charge requirement before release.",
	chargeDrain = "Sustained drain while a charge is held.",
	releaseDrain = "Drain paid on release.",
	missCost = "Extra drain paid on miss.",
	clickCooldown = "Explicit numeric cooldown when the source used a literal number.",
	sourceClickCooldown = "Original cooldown token when the source used a symbolic constant.",
	recovery = "Stationary recovery window after use.",
	swingDelay = "Delay between invocation and contact in the source.",
	damageFactor = "Damage multiplier attached to the intent.",
	penetrationFactor = "Armor penetration modifier attached to the intent.",
	integrityDamageFactor = "Modifier for armor or integrity pressure.",
	minDamage = "Minimum damage floor configured by the intent.",
	maxDamage = "Maximum damage cap configured by the intent.",
	reach = "Portable melee range in tiles or paces.",
	allowOffhand = "Whether the intent permits an occupied off-hand.",
	peelDivisor = "Hits required for armor peeling style intents.",
	isRanged = "Marks projectile or ranged release intents.",
	isGuard = "Marks guard or block style intents.",
	isUnarmed = "Marks body-based intents rather than item-based intents.",
	suppressesAutoAim = "Portable view of the source noaa flag.",
	baseAimTime = "Source baseline aim time used by dynamic ranged intents.",
	sourcePath = "Original BYOND datum path used as the source of truth.",
	notes = "Short note when mechanics were intentionally not ported with the data.",
}

CombatData.IntentOrder = {
	"generic_hit",
	"generic_stab",
	"generic_pick",
	"generic_shoot",
	"generic_arc",
	"generic_swing",
	"unarmed_help",
	"unarmed_grab",
	"unarmed_shove",
	"unarmed_punch",
	"unarmed_claw",
	"mmb_kick",
	"mmb_bite",
	"shield_bash",
	"shield_block",
	"sword_cut",
	"sword_thrust",
	"sword_chop",
	"sword_strike",
	"sword_peel",
	"axe_cut",
	"axe_chop",
	"axe_thrust",
	"axe_bash",
	"polearm_thrust",
	"polearm_cut",
	"polearm_bash",
	"polearm_cast",
	"polearm_rend",
	"polearm_peel",
	"mace_strike",
	"mace_smash",
	"mace_bash",
	"mace_thrust",
	"dagger_cut",
	"dagger_thrust",
	"dagger_pick",
	"dagger_chop",
	"dagger_sucker_punch",
	"flail_strike",
	"flail_smash",
	"flail_bash",
	"whip_lash",
	"whip_crack",
	"whip_punish",
	"crossbow_shoot",
	"crossbow_arc",
	"crossbow_buttstroke",
}

CombatData.Intents = {
	generic_hit = DefineIntent("generic_hit", {
		name = "hit",
		group = "generic",
		attackVerbs = { "hit", "strike" },
		sourcePath = "/datum/intent/hit",
	}),
	generic_stab = DefineIntent("generic_stab", {
		name = "stab",
		group = "generic",
		iconState = "instab",
		attackVerbs = { "stab" },
		animation = "stab",
		damageClass = "stab",
		damageType = "stab",
		sourcePath = "/datum/intent/stab",
	}),
	generic_pick = DefineIntent("generic_pick", {
		name = "pick",
		group = "generic",
		iconState = "inpick",
		attackVerbs = { "picks", "impales" },
		damageClass = "pick",
		damageType = "stab",
		penetrationFactor = 80,
		clickCooldown = 14,
		swingDelay = 12,
		maxDamage = 9999,
		sourcePath = "/datum/intent/pick",
	}),
	generic_shoot = DefineIntent("generic_shoot", {
		name = "shoot",
		group = "generic",
		iconState = "inshoot",
		damageType = "stab",
		isRanged = true,
		chargeTime = 0.1,
		suppressesAutoAim = true,
		sourcePath = "/datum/intent/shoot",
	}),
	generic_arc = DefineIntent("generic_arc", {
		name = "arc",
		group = "generic",
		iconState = "inarc",
		damageType = "blunt",
		isRanged = true,
		suppressesAutoAim = true,
		sourcePath = "/datum/intent/arc",
	}),
	generic_swing = DefineIntent("generic_swing", {
		name = "swing",
		group = "generic",
		iconState = "inshoot",
		damageType = "stab",
		isRanged = true,
		chargeTime = 0.1,
		suppressesAutoAim = true,
		sourcePath = "/datum/intent/swing",
	}),
	unarmed_help = DefineIntent("unarmed_help", {
		name = "touch",
		group = "unarmed",
		iconState = "intouch",
		attackVerbs = {},
		canDodge = false,
		missCost = 0,
		releaseDrain = 0,
		isUnarmed = true,
		suppressesAutoAim = true,
		sourcePath = "/datum/intent/unarmed/help",
	}),
	unarmed_grab = DefineIntent("unarmed_grab", {
		name = "grab",
		group = "unarmed",
		iconState = "ingrab",
		attackVerbs = { "grabs" },
		releaseDrain = 10,
		missCost = 8,
		isUnarmed = true,
		suppressesAutoAim = true,
		sourcePath = "/datum/intent/unarmed/grab",
	}),
	unarmed_shove = DefineIntent("unarmed_shove", {
		name = "shove",
		group = "unarmed",
		iconState = "inshove",
		attackVerbs = { "shoves", "pushes" },
		missCost = 5,
		isUnarmed = true,
		suppressesAutoAim = true,
		sourcePath = "/datum/intent/unarmed/shove",
	}),
	unarmed_punch = DefineIntent("unarmed_punch", {
		name = "punch",
		group = "unarmed",
		iconState = "inpunch",
		attackVerbs = { "punches", "jabs", "clocks", "strikes" },
		animation = "bite",
		damageClass = "punch",
		damageType = "blunt",
		missCost = 4,
		releaseDrain = 1,
		clickCooldown = 10,
		integrityDamageFactor = 0.5,
		isUnarmed = true,
		sourcePath = "/datum/intent/unarmed/punch",
	}),
	unarmed_claw = DefineIntent("unarmed_claw", {
		name = "claw",
		group = "unarmed",
		attackVerbs = { "mauls", "scratches", "claws" },
		animation = "blank22",
		damageClass = "cut",
		damageType = "slash",
		missCost = 5,
		releaseDrain = 4,
		penetrationFactor = 10,
		isUnarmed = true,
		sourcePath = "/datum/intent/unarmed/claw",
	}),
	mmb_kick = DefineIntent("mmb_kick", {
		name = "kick",
		group = "mmb",
		attackVerbs = { "kicks" },
		animation = "kick",
		missCost = 20,
		swingDelay = 5,
		isUnarmed = true,
		sourcePath = "/datum/intent/kick",
	}),
	mmb_bite = DefineIntent("mmb_bite", {
		name = "bite",
		group = "mmb",
		attackVerbs = { "bites" },
		animation = "bite",
		isUnarmed = true,
		sourcePath = "/datum/intent/bite",
	}),
	shield_bash = DefineIntent("shield_bash", {
		name = "bash",
		group = "shield",
		iconState = "inbash",
		damageType = "blunt",
		sourcePath = "/datum/intent/shield/bash",
	}),
	shield_block = DefineIntent("shield_block", {
		name = "block",
		group = "shield",
		iconState = "inblock",
		attackVerbs = {},
		isGuard = true,
		chargeTime = 1,
		damageType = "blunt",
		sourcePath = "/datum/intent/shield/block",
	}),
	sword_cut = DefineIntent("sword_cut", {
		name = "strike",
		group = "sword",
		iconState = "incut",
		attackVerbs = { "cuts", "slashes" },
		animation = "cut",
		damageClass = "cut",
		damageType = "slash",
		damageFactor = 1.1,
		sourcePath = "/datum/intent/sword/cut",
	}),
	sword_thrust = DefineIntent("sword_thrust", {
		name = "stab",
		group = "sword",
		iconState = "instab",
		attackVerbs = { "stabs" },
		animation = "stab",
		damageClass = "stab",
		damageType = "stab",
		penetrationFactor = 20,
		sourcePath = "/datum/intent/sword/thrust",
	}),
	sword_chop = DefineIntent("sword_chop", {
		name = "chop",
		group = "sword",
		iconState = "inchop",
		attackVerbs = { "chops", "hacks" },
		animation = "chop",
		damageClass = "chop",
		damageType = "slash",
		penetrationFactor = 30,
		damageFactor = 1.0,
		swingDelay = 8,
		sourcePath = "/datum/intent/sword/chop",
	}),
	sword_strike = DefineIntent("sword_strike", {
		name = "pommel strike",
		group = "sword",
		iconState = "instrike",
		attackVerbs = { "bashes", "clubs" },
		animation = "strike",
		damageClass = "blunt",
		damageType = "blunt",
		sourcePath = "/datum/intent/sword/strike",
	}),
	sword_peel = DefineIntent("sword_peel", {
		name = "armor peel",
		group = "sword",
		iconState = "inpeel",
		attackVerbs = { "peels" },
		animation = "cut",
		damageClass = "peel",
		damageType = "slash",
		damageFactor = 0.01,
		peelDivisor = 4,
		sourcePath = "/datum/intent/sword/peel",
	}),
	axe_cut = DefineIntent("axe_cut", {
		name = "cut",
		group = "axe",
		iconState = "incut",
		attackVerbs = { "cuts", "slashes" },
		animation = "cut",
		damageClass = "cut",
		damageType = "slash",
		penetrationFactor = 15,
		damageFactor = 1.1,
		sourcePath = "/datum/intent/axe/cut",
	}),
	axe_chop = DefineIntent("axe_chop", {
		name = "chop",
		group = "axe",
		iconState = "inchop",
		attackVerbs = { "chops", "hacks" },
		animation = "chop",
		damageClass = "chop",
		damageType = "slash",
		penetrationFactor = 30,
		damageFactor = 1.2,
		swingDelay = 8,
		clickCooldown = 14,
		sourcePath = "/datum/intent/axe/chop",
	}),
	axe_thrust = DefineIntent("axe_thrust", {
		name = "stab",
		group = "axe",
		iconState = "instab",
		attackVerbs = { "stabs" },
		animation = "stab",
		damageClass = "stab",
		damageType = "stab",
		damageFactor = 0.9,
		sourcePath = "/datum/intent/axe/thrust",
	}),
	axe_bash = DefineIntent("axe_bash", {
		name = "bash",
		group = "axe",
		iconState = "inbash",
		attackVerbs = { "bashes", "clubs" },
		animation = "strike",
		damageClass = "blunt",
		damageType = "blunt",
		swingDelay = 5,
		sourcePath = "/datum/intent/axe/bash",
	}),
	polearm_thrust = DefineIntent("polearm_thrust", {
		name = "thrust",
		group = "polearm",
		iconState = "instab",
		attackVerbs = { "thrusts" },
		animation = "stab",
		damageClass = "stab",
		damageType = "stab",
		penetrationFactor = 55,
		reach = 2,
		sourceClickCooldown = "CLICK_CD_CHARGED",
		sourcePath = "/datum/intent/spear/thrust",
	}),
	polearm_cut = DefineIntent("polearm_cut", {
		name = "cut",
		group = "polearm",
		iconState = "incut",
		attackVerbs = { "cuts", "slashes" },
		damageClass = "cut",
		damageType = "slash",
		damageFactor = 1.0,
		reach = 2,
		sourcePath = "/datum/intent/spear/cut",
	}),
	polearm_bash = DefineIntent("polearm_bash", {
		name = "bash",
		group = "polearm",
		iconState = "inbash",
		attackVerbs = { "bashes", "strikes" },
		damageClass = "blunt",
		damageType = "blunt",
		sourcePath = "/datum/intent/spear/bash",
	}),
	polearm_cast = DefineIntent("polearm_cast", {
		name = "cast",
		group = "polearm",
		iconState = "inuse",
		attackVerbs = {},
		chargeTime = 0,
		missCost = 0,
		damageType = "stab",
		isRanged = true,
		suppressesAutoAim = true,
		sourcePath = "/datum/intent/spear/cast",
	}),
	polearm_rend = DefineIntent("polearm_rend", {
		name = "rend",
		group = "polearm",
		iconState = "inrend",
		attackVerbs = { "rends", "cleaves" },
		animation = "chop",
		damageClass = "chop",
		damageType = "slash",
		damageFactor = 2.5,
		penetrationFactor = 0,
		reach = 1,
		swingDelay = 15,
		sourceClickCooldown = "CLICK_CD_CHARGED",
		missCost = 10,
		integrityDamageFactor = 0.05,
		sourcePath = "/datum/intent/rend",
	}),
	polearm_peel = DefineIntent("polearm_peel", {
		name = "armor peel",
		group = "polearm",
		iconState = "inpeel",
		attackVerbs = { "snags" },
		animation = "cut",
		damageClass = "peel",
		damageType = "slash",
		damageFactor = 0.01,
		peelDivisor = 5,
		reach = 2,
		swingDelay = 5,
		sourceClickCooldown = "CLICK_CD_CHARGED",
		sourcePath = "/datum/intent/partizan/peel",
	}),
	mace_strike = DefineIntent("mace_strike", {
		name = "strike",
		group = "mace",
		iconState = "instrike",
		attackVerbs = { "strikes", "hits" },
		damageClass = "blunt",
		damageType = "blunt",
		sourcePath = "/datum/intent/mace/strike",
	}),
	mace_smash = DefineIntent("mace_smash", {
		name = "smash",
		group = "mace",
		iconState = "insmash",
		attackVerbs = { "smashes" },
		damageClass = "smash",
		damageType = "blunt",
		chargeTime = 5,
		chargeDrain = 1,
		notes = "Source mechanic adds strength-based knockback; only the base data is ported here.",
		sourcePath = "/datum/intent/mace/smash",
	}),
	mace_bash = DefineIntent("mace_bash", {
		name = "bash",
		group = "mace",
		iconState = "inbash",
		attackVerbs = { "bashes", "strikes" },
		damageClass = "blunt",
		damageType = "blunt",
		sourcePath = "/datum/intent/mace/bash",
	}),
	mace_thrust = DefineIntent("mace_thrust", {
		name = "thrust",
		group = "mace",
		iconState = "instab",
		attackVerbs = { "thrusts" },
		animation = "stab",
		damageClass = "stab",
		damageType = "stab",
		penetrationFactor = 25,
		damageFactor = 0.9,
		reach = 2,
		recovery = 30,
		sourceClickCooldown = "CLICK_CD_CHARGED",
		sourcePath = "/datum/intent/mace/rangedthrust",
	}),
	dagger_cut = DefineIntent("dagger_cut", {
		name = "cut",
		group = "dagger",
		iconState = "incut",
		attackVerbs = { "cuts", "slashes" },
		animation = "cut",
		damageClass = "cut",
		damageType = "slash",
		clickCooldown = 10,
		sourcePath = "/datum/intent/dagger/cut",
	}),
	dagger_thrust = DefineIntent("dagger_thrust", {
		name = "thrust",
		group = "dagger",
		iconState = "instab",
		attackVerbs = { "thrusts" },
		animation = "stab",
		damageClass = "stab",
		damageType = "stab",
		penetrationFactor = 40,
		clickCooldown = 8,
		sourcePath = "/datum/intent/dagger/thrust",
	}),
	dagger_pick = DefineIntent("dagger_pick", {
		name = "icepick stab",
		group = "dagger",
		iconState = "inpick",
		attackVerbs = { "stabs", "impales" },
		damageClass = "pick",
		damageType = "stab",
		penetrationFactor = 80,
		damageFactor = 1.1,
		clickCooldown = 14,
		swingDelay = 12,
		sourcePath = "/datum/intent/dagger/thrust/pick",
	}),
	dagger_chop = DefineIntent("dagger_chop", {
		name = "chop",
		group = "dagger",
		iconState = "inchop",
		attackVerbs = { "chops" },
		animation = "chop",
		damageClass = "chop",
		damageType = "slash",
		penetrationFactor = 10,
		damageFactor = 1.5,
		swingDelay = 5,
		clickCooldown = 10,
		sourcePath = "/datum/intent/dagger/chop",
	}),
	dagger_sucker_punch = DefineIntent("dagger_sucker_punch", {
		name = "unevadable punch",
		group = "dagger",
		iconState = "inpunch",
		description = "Low-damage jab that bypasses parry and dodge in the source game.",
		attackVerbs = { "punches", "jabs", "clocks" },
		animation = "strike",
		damageClass = "blunt",
		damageType = "blunt",
		damageFactor = 0.6,
		clickCooldown = 14,
		recovery = 10,
		canParry = false,
		canDodge = false,
		sourcePath = "/datum/intent/dagger/sucker_punch",
	}),
	flail_strike = DefineIntent("flail_strike", {
		name = "flailing strike",
		group = "flail",
		iconState = "instrike",
		attackVerbs = { "strikes", "sweeps" },
		damageClass = "blunt",
		damageType = "blunt",
		damageFactor = 1.1,
		sourcePath = "/datum/intent/flail/strike",
	}),
	flail_smash = DefineIntent("flail_smash", {
		name = "flailing smash",
		group = "flail",
		iconState = "insmash",
		attackVerbs = { "smashes" },
		damageClass = "smash",
		damageType = "blunt",
		chargeTime = 0.8,
		chargeDrain = 1.5,
		damageFactor = 1.5,
		notes = "Source mechanic adds strength-based knockback; only the base data is ported here.",
		sourcePath = "/datum/intent/flail/smash",
	}),
	flail_bash = DefineIntent("flail_bash", {
		name = "bash with handle",
		group = "flail",
		iconState = "inbash",
		attackVerbs = { "handlewhips", "bashes", "strikes" },
		animation = "strike",
		damageClass = "blunt",
		damageType = "blunt",
		damageFactor = 0.8,
		sourcePath = "/datum/intent/flail/bash",
	}),
	whip_lash = DefineIntent("whip_lash", {
		name = "lash",
		group = "whip",
		iconState = "inlash",
		attackVerbs = { "lashes", "cracks" },
		damageClass = "lashing",
		damageType = "slash",
		penetrationFactor = 30,
		reach = 3,
		recovery = 7,
		sourcePath = "/datum/intent/whip/lash",
	}),
	whip_crack = DefineIntent("whip_crack", {
		name = "crack",
		group = "whip",
		iconState = "incrack",
		attackVerbs = { "cracks", "strikes" },
		damageClass = "cut",
		damageType = "slash",
		damageFactor = 1.1,
		penetrationFactor = 20,
		reach = 2,
		recovery = 10,
		sourcePath = "/datum/intent/whip/crack",
	}),
	whip_punish = DefineIntent("whip_punish", {
		name = "punish",
		group = "whip",
		iconState = "inpunish",
		attackVerbs = { "lashes", "cracks" },
		damageClass = "punish",
		damageType = "slash",
		damageFactor = 1.2,
		recovery = 5,
		reach = 1,
		sourcePath = "/datum/intent/whip/punish",
	}),
	crossbow_shoot = DefineIntent("crossbow_shoot", {
		name = "shoot",
		group = "crossbow",
		iconState = "inshoot",
		damageType = "stab",
		isRanged = true,
		chargeDrain = 0,
		chargeTime = 0.1,
		baseAimTime = 40,
		suppressesAutoAim = true,
		sourcePath = "/datum/intent/shoot/crossbow",
	}),
	crossbow_arc = DefineIntent("crossbow_arc", {
		name = "arc",
		group = "crossbow",
		iconState = "inarc",
		damageType = "blunt",
		isRanged = true,
		chargeDrain = 0,
		chargeTime = 1,
		baseAimTime = 40,
		suppressesAutoAim = true,
		sourcePath = "/datum/intent/arc/crossbow",
	}),
	crossbow_buttstroke = DefineIntent("crossbow_buttstroke", {
		name = "buttstroke",
		group = "crossbow",
		iconState = "instrike",
		attackVerbs = { "strikes", "buttstrokes" },
		damageClass = "blunt",
		damageType = "blunt",
		damageFactor = 1.1,
		sourcePath = "/datum/intent/buttstroke",
	}),
}

-------------------------------------------------------------------------------
-- Weapon intent modes.
-- This is a lightweight layer that can later be supplied by equipment while
-- still flowing through the action intent API.
-------------------------------------------------------------------------------

CombatData.WeaponIntentModeOrder = {
	"fint",
	"aimed",
	"swift",
	"strong",
	"defend",
	"weak",
}

CombatData.WeaponIntentModes = {
	fint = {
		id = "fint",
		label = "Fint",
		description = "Bait the target and, on right-clicking the doll, try to shut down dodge and parry if the attacker qualifies.",
		accuracyModifier = 0,
		cooldownMultiplier = 1.0,
		damageMultiplier = 1.0,
		rightClickAction = "apply_fint",
		fintDuration = 6,
		requiredMastery = 1,
		requiredIntelligence = 10,
		liveSummary = "Right-click the doll while selected to apply a dodge/parry lock.",
	},
	aimed = {
		id = "aimed",
		label = "Aimed",
		description = "A careful striking mode reserved for future aimed-hit bonuses.",
		accuracyModifier = 0,
		futureAccuracyBonus = 10,
		cooldownMultiplier = 1.0,
		damageMultiplier = 1.0,
		futureSummary = "Will grant extra accuracy once aimed-hit math is wired in.",
	},
	swift = {
		id = "swift",
		label = "Swift",
		description = "Fast strikes with a shorter attack delay.",
		accuracyModifier = 0,
		cooldownMultiplier = 1.0,
		cooldownModifier = -0.5,
		damageMultiplier = 1.0,
		liveSummary = "Cuts attack cooldown from 1.5s to 1.0s.",
	},
	strong = {
		id = "strong",
		label = "Strong",
		description = "Heavy blow that should hit as if it had one extra point of Strength and spend more stamina.",
		accuracyModifier = 0,
		cooldownMultiplier = 1.0,
		damageMultiplier = 1.0,
		strengthBonus = 1,
		staminaMultiplier = 1.35,
		futureSummary = "Stored as +1 Strength damage and extra stamina cost for the future damage pass.",
	},
	defend = {
		id = "defend",
		label = "Defend",
		description = "Defensive handling with no attack bonus, meant to improve parry and dodge flow.",
		accuracyModifier = 0,
		cooldownMultiplier = 1.0,
		damageMultiplier = 1.0,
		parryCooldownMultiplier = 0.0,
		dodgeBonus = 4,
		defenseBias = true,
		futureSummary = "Stored as no parry cooldown and a small dodge bonus for the future defense pass.",
	},
	weak = {
		id = "weak",
		label = "Weak",
		description = "Deliberately soft strike that should deal only twenty percent of normal damage.",
		accuracyModifier = 0,
		cooldownMultiplier = 1.0,
		damageMultiplier = 0.2,
		futureSummary = "Stored as 20% normal damage for the future damage pass.",
	},
}

CombatData.IntentGroups = {
	generic = {},
	unarmed = {},
	mmb = {},
	shield = {},
	sword = {},
	axe = {},
	polearm = {},
	mace = {},
	dagger = {},
	flail = {},
	whip = {},
	crossbow = {},
}

for _, intentId in ipairs(CombatData.IntentOrder) do
	local intent = CombatData.Intents[intentId]

	if intent and CombatData.IntentGroups[intent.group] then
		table.insert(CombatData.IntentGroups[intent.group], intentId)
	end
end

-------------------------------------------------------------------------------
-- Weapon intent archetypes.
-- These are base loadouts distilled from Azure-Peak weapon families, not a
-- one-to-one port of every concrete weapon item.
-------------------------------------------------------------------------------

CombatData.WeaponProfileOrder = {
	"generic",
	"unarmed",
	"shield",
	"sword",
	"axe",
	"polearm",
	"mace",
	"dagger",
	"flail",
	"whip",
	"crossbow",
}

CombatData.WeaponProfiles = {
	generic = {
		id = "generic",
		label = "Generic Weapon",
		description = "Fallback profile for improvised or non-specialized weapons.",
		defaultIntents = { "generic_hit" },
		alternateIntents = { "generic_stab", "generic_pick" },
		sourceExamples = {
			"/datum/intent/hit",
			"/obj/item/rogueweapon",
		},
	},
	unarmed = {
		id = "unarmed",
		label = "Unarmed",
		description = "Hand-based baseline intents plus core MMB body actions.",
		defaultIntents = { "unarmed_help", "unarmed_grab", "unarmed_shove", "unarmed_punch" },
		alternateIntents = { "unarmed_claw", "mmb_kick", "mmb_bite" },
		sourceExamples = {
			"/datum/intent/unarmed/help",
			"/datum/intent/unarmed/punch",
			"/datum/intent/kick",
			"/datum/intent/bite",
		},
	},
	shield = {
		id = "shield",
		label = "Shield",
		description = "Defensive off-hand profile built around bashing and active blocking.",
		defaultIntents = { "shield_bash", "shield_block" },
		sourceExamples = {
			"/obj/item/rogueweapon/shield",
		},
	},
	sword = {
		id = "sword",
		label = "Sword",
		description = "Balanced blade profile with cut and thrust as the default core.",
		defaultIntents = { "sword_cut", "sword_thrust" },
		grippedIntents = { "sword_cut", "sword_thrust", "sword_chop", "sword_peel" },
		alternateIntents = { "sword_strike" },
		sourceExamples = {
			"/obj/item/rogueweapon",
			"/datum/intent/sword/cut",
			"/datum/intent/sword/thrust",
		},
	},
	axe = {
		id = "axe",
		label = "Axe",
		description = "Hack-focused weapon family with chop, cut, bash, and some thrust variants.",
		defaultIntents = { "axe_cut", "axe_chop", "axe_bash" },
		grippedIntents = { "axe_cut", "axe_chop", "axe_bash", "sword_peel" },
		alternateIntents = { "axe_thrust" },
		sourceExamples = {
			"/obj/item/rogueweapon/stoneaxe/woodcut",
			"/obj/item/rogueweapon/stoneaxe/battle",
		},
	},
	polearm = {
		id = "polearm",
		label = "Polearm",
		description = "Reach-oriented spear or polearm family with thrust, cut, and utility variants.",
		defaultIntents = { "polearm_thrust", "polearm_cut", "polearm_bash" },
		alternateIntents = { "polearm_cast", "polearm_rend", "polearm_peel" },
		sourceExamples = {
			"/datum/intent/spear/thrust",
			"/datum/intent/spear/cut",
			"/datum/intent/partizan/peel",
		},
	},
	mace = {
		id = "mace",
		label = "Mace",
		description = "Impact-heavy blunt family centered on strike and smash pressure.",
		defaultIntents = { "mace_strike" },
		grippedIntents = { "mace_strike", "mace_smash", "mace_bash" },
		alternateIntents = { "mace_thrust" },
		sourceExamples = {
			"/obj/item/rogueweapon/mace",
			"/datum/intent/mace/smash",
		},
	},
	dagger = {
		id = "dagger",
		label = "Dagger",
		description = "Close-range precision family built around thrusting and quick cuts.",
		defaultIntents = { "dagger_cut", "dagger_thrust", "dagger_chop" },
		alternateIntents = { "dagger_pick", "dagger_sucker_punch" },
		sourceExamples = {
			"/obj/item/rogueweapon/huntingknife",
			"/datum/intent/dagger/thrust/pick",
		},
	},
	flail = {
		id = "flail",
		label = "Flail",
		description = "Chain weapon family with sweeping strike and committed smash options.",
		defaultIntents = { "flail_strike", "flail_smash", "flail_bash" },
		sourceExamples = {
			"/obj/item/rogueweapon/flail",
		},
	},
	whip = {
		id = "whip",
		label = "Whip",
		description = "Range-skewed lash family with crack and punish sidegrades.",
		defaultIntents = { "whip_lash", "whip_crack", "whip_punish" },
		sourceExamples = {
			"/obj/item/rogueweapon/whip",
		},
	},
	crossbow = {
		id = "crossbow",
		label = "Crossbow",
		description = "Projectile profile with direct shot, arc shot, and close buttstroke fallback.",
		defaultIntents = { "crossbow_shoot", "crossbow_arc", "crossbow_buttstroke" },
		sourceExamples = {
			"/obj/item/gun/ballistic/revolver/grenadelauncher/crossbow",
		},
	},
}

function CombatData:GetStat(statId)
	return self.Stats[statId]
end

function CombatData:GetIntent(intentId)
	return self.Intents[intentId]
end

function CombatData:GetWeaponIntentMode(modeId)
	return self.WeaponIntentModes[modeId]
end

function CombatData:GetWeaponProfile(profileId)
	return self.WeaponProfiles[profileId]
end
